### PR TITLE
Make about page consistent with rest of the UI

### PR DESCRIPTION
**Pull request by ArchKudo**
To be consistent with the rest of the app I switched the about page to use the ~default~ dark theme

In this PR:
- [ ] Use `ThemeHelper.setTheme` in AboutActivity
- [ ] Use custom cardView with modified background color and borders

### CODE REVIEW

**Comment by adrcotfas** [comment]
This will not bring any consistency because the theme you used is not based on the AppTheme.

**Comment by ArchKudo** [comment]
Thanks for replying! I am really sorry for my previous incomplete attempt but, I took a second plunge and split the AboutActivity into fragments, and set the theme using `ThemeHelper`, but couldn't get it to work, it would be great if you could provide a hint on where to look?

P.S: I am also changing the PR's description so please do take a look..

**Comment by adrcotfas** [comment]
I assume that your PR does not include the changes to make the About page consistent, given your comment. I'll close this PR for now. You'll find a fix in the latest version.

**Comment by ArchKudo** [comment]
Oh! Thanks for the update and, sorry for the trouble... on a side-note, apart from the non-amoled theme, the cards too don't use the material theme's rounded corners
Anyways, thanks for listening!

**Comment by adrcotfas** [comment]
I'm using a library for the About so I cannot control that. 
`implementation 'com.github.daniel-stoneuk:material-about-library:2.4.2'`
Thanks for contributing!

**Pull request closed without merging**
